### PR TITLE
added custom headers support

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
### What does this PR do?

Added ability to set custom HTTP headers

### Motivation

Ability to use plugin with custom HTTP endpoints

### CODE REVIEW

**Review by lukesteensen — APPROVED** [review]

**Review by lukesteensen — CHANGES_REQUESTED** [review]
Looks like there are a few issues in the tests that need addressed as well. Could you take a look at those @AndrewChubatiuk?

**Comment by AndrewChubatiuk** [comment]
hey @lukesteensen, just updated

**Review by lukesteensen — APPROVED** [review]
Thank you!

**Pull request merged**
