### PR TITLE
Fix syntax errors from #25 & add sub-second precision

### PR DESCRIPTION
**Pull request by juzna**
#25 got merged too quickly, before I was able to verify that it works. Unfortunately, it had some errors. This fixes them.

### CODE REVIEW

**Comment by juzna** [comment]
cc @blemale

**Comment by juzna** [comment]
Now fully tested on our stack, sorry for not doing that before.

**Comment by blemale** [comment]
@juzna thanks for the contribution, and it is my bad I should have done a more cautious review.

**Comment by blemale** [comment]
@juzna I merge the PR and we will hopefully do a release today

**Pull request merged**
